// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: enforce_models.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//已知用户名和id，请求jwt
type EnforceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName string `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Route    string `protobuf:"bytes,2,opt,name=route,proto3" json:"route,omitempty"`
	Act      string `protobuf:"bytes,3,opt,name=act,proto3" json:"act,omitempty"`
}

func (x *EnforceRequest) Reset() {
	*x = EnforceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enforce_models_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnforceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnforceRequest) ProtoMessage() {}

func (x *EnforceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enforce_models_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnforceRequest.ProtoReflect.Descriptor instead.
func (*EnforceRequest) Descriptor() ([]byte, []int) {
	return file_enforce_models_proto_rawDescGZIP(), []int{0}
}

func (x *EnforceRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *EnforceRequest) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *EnforceRequest) GetAct() string {
	if x != nil {
		return x.Act
	}
	return ""
}

type EnforceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pass bool `protobuf:"varint,1,opt,name=pass,proto3" json:"pass,omitempty"`
}

func (x *EnforceResponse) Reset() {
	*x = EnforceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enforce_models_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnforceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnforceResponse) ProtoMessage() {}

func (x *EnforceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enforce_models_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnforceResponse.ProtoReflect.Descriptor instead.
func (*EnforceResponse) Descriptor() ([]byte, []int) {
	return file_enforce_models_proto_rawDescGZIP(), []int{1}
}

func (x *EnforceResponse) GetPass() bool {
	if x != nil {
		return x.Pass
	}
	return false
}

var File_enforce_models_proto protoreflect.FileDescriptor

var file_enforce_models_proto_rawDesc = []byte{
	0x0a, 0x14, 0x65, 0x6e, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x55, 0x0a, 0x0e, 0x45, 0x6e, 0x66, 0x6f, 0x72, 0x63,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61,
	0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x63, 0x74, 0x22, 0x25, 0x0a,
	0x0f, 0x45, 0x6e, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04,
	0x70, 0x61, 0x73, 0x73, 0x42, 0x26, 0x5a, 0x24, 0x6a, 0x64, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x2d,
	0x63, 0x61, 0x73, 0x62, 0x69, 0x6e, 0x2d, 0x65, 0x6e, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x72, 0x2f,
	0x73, 0x72, 0x63, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_enforce_models_proto_rawDescOnce sync.Once
	file_enforce_models_proto_rawDescData = file_enforce_models_proto_rawDesc
)

func file_enforce_models_proto_rawDescGZIP() []byte {
	file_enforce_models_proto_rawDescOnce.Do(func() {
		file_enforce_models_proto_rawDescData = protoimpl.X.CompressGZIP(file_enforce_models_proto_rawDescData)
	})
	return file_enforce_models_proto_rawDescData
}

var file_enforce_models_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_enforce_models_proto_goTypes = []interface{}{
	(*EnforceRequest)(nil),  // 0: EnforceRequest
	(*EnforceResponse)(nil), // 1: EnforceResponse
}
var file_enforce_models_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enforce_models_proto_init() }
func file_enforce_models_proto_init() {
	if File_enforce_models_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_enforce_models_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnforceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_enforce_models_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnforceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_enforce_models_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enforce_models_proto_goTypes,
		DependencyIndexes: file_enforce_models_proto_depIdxs,
		MessageInfos:      file_enforce_models_proto_msgTypes,
	}.Build()
	File_enforce_models_proto = out.File
	file_enforce_models_proto_rawDesc = nil
	file_enforce_models_proto_goTypes = nil
	file_enforce_models_proto_depIdxs = nil
}
