// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.0
// source: enforce_services.proto

package services

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EnforceServiceClient is the client API for EnforceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EnforceServiceClient interface {
	Enforce(ctx context.Context, in *EnforceRequest, opts ...grpc.CallOption) (*EnforceResponse, error)
}

type enforceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEnforceServiceClient(cc grpc.ClientConnInterface) EnforceServiceClient {
	return &enforceServiceClient{cc}
}

func (c *enforceServiceClient) Enforce(ctx context.Context, in *EnforceRequest, opts ...grpc.CallOption) (*EnforceResponse, error) {
	out := new(EnforceResponse)
	err := c.cc.Invoke(ctx, "/EnforceService/Enforce", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnforceServiceServer is the server API for EnforceService service.
// All implementations must embed UnimplementedEnforceServiceServer
// for forward compatibility
type EnforceServiceServer interface {
	Enforce(context.Context, *EnforceRequest) (*EnforceResponse, error)
	mustEmbedUnimplementedEnforceServiceServer()
}

// UnimplementedEnforceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEnforceServiceServer struct {
}

func (UnimplementedEnforceServiceServer) Enforce(context.Context, *EnforceRequest) (*EnforceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Enforce not implemented")
}
func (UnimplementedEnforceServiceServer) mustEmbedUnimplementedEnforceServiceServer() {}

// UnsafeEnforceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnforceServiceServer will
// result in compilation errors.
type UnsafeEnforceServiceServer interface {
	mustEmbedUnimplementedEnforceServiceServer()
}

func RegisterEnforceServiceServer(s grpc.ServiceRegistrar, srv EnforceServiceServer) {
	s.RegisterService(&EnforceService_ServiceDesc, srv)
}

func _EnforceService_Enforce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnforceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnforceServiceServer).Enforce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EnforceService/Enforce",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnforceServiceServer).Enforce(ctx, req.(*EnforceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EnforceService_ServiceDesc is the grpc.ServiceDesc for EnforceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EnforceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "EnforceService",
	HandlerType: (*EnforceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enforce",
			Handler:    _EnforceService_Enforce_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "enforce_services.proto",
}
